### ISSUE TITLE
How does this avoid spam?

### ISSUE THREAD

**Issue by nelsonic** [diasdavid/mailgun-validate-email#4]
@diasdavid readme says this will help avoid spam. *How*?
or does it avoid allowing people to register with *fake* email address and/or wasting time sending emails to *invalid* emails?
Can I clarify this in the readme and send you a PR?
Also, can I clarify for people ***why*** they would use this instead of (or in *addition* to) `Joi.string().email();` (email format validation).
Abraço!

**Comment by diasdavid** [comment]
There is a lot of phishing out there, a great part of it don't even go through the effort of creating fake emails, this module can help you catch all of that low hanging fruit. Thanks for the PR btw!
