### ISSUE TITLE
SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by nidhi95** [diasdavid/mailgun-validate-email#6]
undefined:0

^
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Request._callback (D:\Share\Node Projects\iphoneunlock\trunk\node_modules\mailgun-validate-email\src\index.js:20:21)
    at Request.self.callback (D:\Share\Node Projects\iphoneunlock\trunk\node_modules\request\request.js:344:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (D:\Share\Node Projects\iphoneunlock\trunk\node_modules\request\request.js:1239:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (D:\Share\Node Projects\iphoneunlock\trunk\node_modules\request\request.js:1187:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickDomainCallback (node.js:381:11)

**Comment by diasdavid** [comment]
Hi! thank you for the bug report, but I'm being unable to reproduce, can you tell me how to reproduce?

**Comment by camj256** [comment]
Yeah, I get this from time to time too!

**Comment by camj256** [comment]
So we do a few hundred emails a day. On further inspection I'm seeing this happen about 20% today which is totally messing up our lead pipeline with that crash. Something is up with the JSON parse. I'm too lazy to fork it on a saturday but I would probably put some try catch on the parse. I suspect in some odd case (failure on mailguns end) that they aren't returning JSON or some sort of blank / incomplete response. Either way this error is bad enough that I have to disable email validation right now.

**Comment by diasdavid** [comment]
Ouch, sorry to hear that, going to add that catch ASAP today

**Comment by diasdavid** [comment]
#8 should fix it @nidhi95 

@camj256 thank you for catching and making the suggestion

**Comment by camj256** [comment]
I forked and added console.log("Unable to Parse MailGun Response: res.request.response.body"); to the fail.

This really shouldn't ever happen so I'll keep an eye out for it and let you guys know in the next day or two (if I see it) what it was trying to parse.

**Comment by jeveloper** [comment]
This happens when mailgun api returns empty body.

**Comment by diasdavid** [comment]
@jeveloper have you tried the new version?

**Comment by jeveloper** [comment]
@diasdavid i have rewritten the module myself and altered it , plus switched to v3 as it seems to be preferred version. I should note that depending on your account and your api key , it may or may not return a body (without a warning and still be status 200)
thank you  for good work though

**Comment by camj256** [comment]
I haven't had this error happen since I opened this issue. I would guess @jeveloper is right though. You might just add a check for an empty body and throw some 'empty body' error or something so we don't have to see that ugly parse error.

**Comment by diasdavid** [comment]
@jeveloper would you like to submit a PR with the updated changes?

@camj256 I've added that check, initially thought that the try catch would be enough https://github.com/diasdavid/mailgun-validate-email/blob/master/src/index.js#L23-L28, but now also added a explicit error for when the body is empty https://github.com/diasdavid/mailgun-validate-email/blob/master/src/index.js#L20-L22, I hope this helps :)

**Comment by jeveloper** [comment]
i think you got it fixed the same way, try catch , that should catch if 200 + empty body , since parsing wouldnt work

**Comment by diasdavid** [comment]
I'll call this issue with solved then :)
