### ISSUE TITLE
Update to v3

### ISSUE THREAD

**Issue by jeveloper** [diasdavid/mailgun-validate-email#9]
It appears that its time to switch to their latest API Version

According to documentation:

curl -G --user 'api:pubkey-5ogiflzbnjrljiky49qxsiozqef5jxp7' -G \
    https://api.mailgun.net/v3/address/validate \
    --data-urlencode address='foo@mailgun.net'

**Comment by diasdavid** [comment]
@jeveloper available to submit a PR? thanks for bringing this up

**Comment by jeveloper** [comment]
You bet
Just did a bunch of improvements , hope you don't mind.

https://github.com/diasdavid/mailgun-validate-email/pull/10
